Add files via upload
add random task composition file, to be merged into the env class; need to check the loading function, get AttributeError: 'NoneType' object has no attribute 'grid'